"""empty message

Revision ID: 455205a887ce
Revises: a315f633fb06
Create Date: 2024-08-27 08:39:35.265276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455205a887ce'
down_revision = 'a315f633fb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(),
               nullable=False)

    # ### end Alembic commands ###
