"""empty message

Revision ID: a315f633fb06
Revises: 1c9710d356b4
Create Date: 2024-08-25 17:10:00.717750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a315f633fb06'
down_revision = '1c9710d356b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('profile_image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
