"""empty message

Revision ID: 2e6ea9d8a6be
Revises: d05d3f15fb9b
Create Date: 2025-07-01 14:49:11.025587

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6ea9d8a6be'
down_revision = "d05d3f15fb9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index('idx_attendances_event_user')
        batch_op.drop_index('idx_attendances_user_event')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comments_parent_created')
        batch_op.drop_index('idx_comments_post_created')
        batch_op.drop_index('idx_comments_user_created')

    with op.batch_alter_table('event_images', schema=None) as batch_op:
        batch_op.drop_index('idx_event_images_event')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_created_at')
        batch_op.drop_index('idx_events_date_range')
        batch_op.drop_index('idx_events_end_date')
        batch_op.drop_index('idx_events_future')
        batch_op.drop_index('idx_events_group_dates')
        batch_op.drop_index('idx_events_group_id')
        batch_op.drop_index('idx_events_start_date')
        batch_op.drop_index('idx_events_type_date')
        batch_op.drop_index('idx_events_venue_id')

    with op.batch_alter_table('group_images', schema=None) as batch_op:
        batch_op.drop_index('idx_group_images_group')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('idx_groups_city')
        batch_op.drop_index('idx_groups_created_at')
        batch_op.drop_index('idx_groups_location')
        batch_op.drop_index('idx_groups_organizer_created')
        batch_op.drop_index('idx_groups_organizer_id')
        batch_op.drop_index('idx_groups_state')
        batch_op.drop_index('idx_groups_type')
        batch_op.drop_index('idx_groups_type_created')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('idx_likes_post_user')
        batch_op.drop_index('idx_likes_user_post')

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('idx_memberships_group_user')
        batch_op.drop_index('idx_memberships_user_group')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_posts_created_at')
        batch_op.drop_index('idx_posts_creator')
        batch_op.drop_index('idx_posts_creator_created')
        batch_op.drop_index('idx_posts_title')
        batch_op.drop_index('idx_posts_updated_at')
        batch_op.drop_index('idx_posts_updated_desc')
        batch_op.create_index(batch_op.f('ix_posts_id'), ['id'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('idx_tags_name')

    with op.batch_alter_table('user_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_user_tags_tag_user')
        batch_op.drop_index('idx_user_tags_user_tag')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_active')
        batch_op.drop_index('idx_users_created_at')
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('idx_users_email_username')
        batch_op.drop_index('idx_users_first_name')
        batch_op.drop_index('idx_users_last_name')
        batch_op.drop_index('idx_users_profile_search')
        batch_op.drop_index('idx_users_username')
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index('idx_venues_coordinates')
        batch_op.drop_index('idx_venues_group_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index('idx_venues_group_location', ['group_id', 'city', 'state'], unique=False)
        batch_op.create_index('idx_venues_coordinates', ['latitude', 'longitude'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.create_index('idx_users_username', ['username'], unique=False)
        batch_op.create_index('idx_users_profile_search', ['first_name', 'last_name'], unique=False)
        batch_op.create_index('idx_users_last_name', ['last_name'], unique=False)
        batch_op.create_index('idx_users_first_name', ['first_name'], unique=False)
        batch_op.create_index('idx_users_email_username', ['email', 'username'], unique=False)
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_users_active', ['created_at'], unique=False)

    with op.batch_alter_table('user_tags', schema=None) as batch_op:
        batch_op.create_index('idx_user_tags_user_tag', ['user_id', 'tag_id'], unique=False)
        batch_op.create_index('idx_user_tags_tag_user', ['tag_id', 'user_id'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('idx_tags_name', ['name'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_id'))
        batch_op.create_index('idx_posts_updated_desc', ['updated_at'], unique=False)
        batch_op.create_index('idx_posts_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('idx_posts_title', ['title'], unique=False)
        batch_op.create_index('idx_posts_creator_created', ['creator', 'created_at'], unique=False)
        batch_op.create_index('idx_posts_creator', ['creator'], unique=False)
        batch_op.create_index('idx_posts_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('idx_memberships_user_group', ['user_id', 'group_id'], unique=False)
        batch_op.create_index('idx_memberships_group_user', ['group_id', 'user_id'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index('idx_likes_user_post', ['user_id', 'post_id'], unique=False)
        batch_op.create_index('idx_likes_post_user', ['post_id', 'user_id'], unique=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index('idx_groups_type_created', ['type', 'created_at'], unique=False)
        batch_op.create_index('idx_groups_type', ['type'], unique=False)
        batch_op.create_index('idx_groups_state', ['state'], unique=False)
        batch_op.create_index('idx_groups_organizer_id', ['organizer_id'], unique=False)
        batch_op.create_index('idx_groups_organizer_created', ['organizer_id', 'created_at'], unique=False)
        batch_op.create_index('idx_groups_location', ['city', 'state'], unique=False)
        batch_op.create_index('idx_groups_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_groups_city', ['city'], unique=False)

    with op.batch_alter_table('group_images', schema=None) as batch_op:
        batch_op.create_index('idx_group_images_group', ['group_id', 'created_at'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_venue_id', ['venue_id'], unique=False)
        batch_op.create_index('idx_events_type_date', ['type', 'start_date'], unique=False)
        batch_op.create_index('idx_events_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_events_group_id', ['group_id'], unique=False)
        batch_op.create_index('idx_events_group_dates', ['group_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_events_future', ['start_date'], unique=False)
        batch_op.create_index('idx_events_end_date', ['end_date'], unique=False)
        batch_op.create_index('idx_events_date_range', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_events_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('event_images', schema=None) as batch_op:
        batch_op.create_index('idx_event_images_event', ['event_id', 'created_at'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_comments_post_created', ['post_id', 'created_at'], unique=False)
        batch_op.create_index('idx_comments_parent_created', ['parent_id', 'created_at'], unique=False)

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('idx_attendances_user_event', ['user_id', 'event_id'], unique=False)
        batch_op.create_index('idx_attendances_event_user', ['event_id', 'user_id'], unique=False)

    # ### end Alembic commands ###
