"""empty message

Revision ID: 0d8177d47731
Revises: performance_indexes
Create Date: 2025-06-27 14:45:41.319301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8177d47731'
down_revision = 'performance_indexes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index('idx_attendances_event_id')
        batch_op.drop_index('idx_attendances_user_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comments_parent_id')
        batch_op.drop_index('idx_comments_post_id')
        batch_op.drop_index('idx_comments_user_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_group_id')
        batch_op.drop_index('idx_events_start_date')
        batch_op.drop_index('idx_events_type')
        batch_op.drop_index('idx_events_venue_id')
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('idx_groups_city')
        batch_op.drop_index('idx_groups_created_at')
        batch_op.drop_index('idx_groups_name')
        batch_op.drop_index('idx_groups_organizer_id')
        batch_op.drop_index('idx_groups_state')
        batch_op.drop_index('idx_groups_type')
        batch_op.create_index(batch_op.f('ix_groups_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_organizer_id'), ['organizer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_type'), ['type'], unique=False)

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('idx_memberships_group_id')
        batch_op.drop_index('idx_memberships_user_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_posts_created_at')
        batch_op.drop_index('idx_posts_creator')
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_creator'), ['creator'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_title'), ['title'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_created_at')
        batch_op.drop_index('idx_users_first_name')
        batch_op.drop_index('idx_users_last_name')
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.create_index('idx_users_last_name', ['last_name'], unique=False)
        batch_op.create_index('idx_users_first_name', ['first_name'], unique=False)
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_title'))
        batch_op.drop_index(batch_op.f('ix_posts_creator'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.create_index('idx_posts_creator', ['creator'], unique=False)
        batch_op.create_index('idx_posts_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('idx_memberships_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_memberships_group_id', ['group_id'], unique=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_type'))
        batch_op.drop_index(batch_op.f('ix_groups_state'))
        batch_op.drop_index(batch_op.f('ix_groups_organizer_id'))
        batch_op.drop_index(batch_op.f('ix_groups_name'))
        batch_op.drop_index(batch_op.f('ix_groups_created_at'))
        batch_op.drop_index(batch_op.f('ix_groups_city'))
        batch_op.create_index('idx_groups_type', ['type'], unique=False)
        batch_op.create_index('idx_groups_state', ['state'], unique=False)
        batch_op.create_index('idx_groups_organizer_id', ['organizer_id'], unique=False)
        batch_op.create_index('idx_groups_name', ['name'], unique=False)
        batch_op.create_index('idx_groups_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_groups_city', ['city'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_venue_id'))
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_start_date'))
        batch_op.drop_index(batch_op.f('ix_events_name'))
        batch_op.drop_index(batch_op.f('ix_events_group_id'))
        batch_op.drop_index(batch_op.f('ix_events_end_date'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))
        batch_op.create_index('idx_events_venue_id', ['venue_id'], unique=False)
        batch_op.create_index('idx_events_type', ['type'], unique=False)
        batch_op.create_index('idx_events_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_events_group_id', ['group_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_comments_post_id', ['post_id'], unique=False)
        batch_op.create_index('idx_comments_parent_id', ['parent_id'], unique=False)

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('idx_attendances_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_attendances_event_id', ['event_id'], unique=False)

    # ### end Alembic commands ###
